//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroAccounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string loginId { get; set; }
        public string password { get; set; }
        public System.DateTime lastLogin { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime updateDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
