//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroAccounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyRate
    {
        public long id { get; set; }
        public Nullable<decimal> fineGold { get; set; }
        public Nullable<decimal> hallmark { get; set; }
        public Nullable<decimal> hallmarkBuyBack { get; set; }
        public Nullable<decimal> twentyTwoC { get; set; }
        public Nullable<decimal> twentyThreeC { get; set; }
        public Nullable<decimal> silver { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
