//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroAccounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransactionMaster
    {
        public long tId { get; set; }
        public System.DateTime tDate { get; set; }
        public string voucherType { get; set; }
        public Nullable<long> voucherRefNo { get; set; }
        public Nullable<decimal> crAmt { get; set; }
        public Nullable<decimal> drAmt { get; set; }
        public Nullable<long> ledgerId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<long> loginId { get; set; }
    
        public virtual tbl_UserLogiln tbl_UserLogiln { get; set; }
    }
}
