//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroAccounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesDetails
    {
        public long sDetailsId { get; set; }
        public Nullable<long> salesId { get; set; }
        public Nullable<long> productId { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> karat { get; set; }
        public Nullable<decimal> making { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<decimal> qty { get; set; }
    
        public virtual tbl_ItemMaster tbl_ItemMaster { get; set; }
        public virtual tbl_SalesMaster tbl_SalesMaster { get; set; }
    }
}
